name: Multi Stage Demo 

on: [push]

jobs: 
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
      - name: Build The App
        run: echo "Buidling the Application!!!!"
  test:
    name: test Stage 
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Run Test
        run: echo "Running Tests....."
  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy 
        run: echo "Deploying the app on EC2"
